Inve 19535 fix nested combo expansion
sirensolutions/G6 pull request #48
Opened 2022-10-05 15:53 UTC by Verdagio

##### Checklist

- [x] `npm test` passes

##### Description of change

Expands parent combos when child is expanded

https://user-images.githubusercontent.com/15673201/194105489-71bce6b3-616f-4cc5-89e0-7462af7861d6.mov

2022-10-05 15:54 UTC, Verdagio commented
Some minor changes required to get stuff to sit correctly

2022-10-05 15:56 UTC, Verdagio commented on packages/core/src/global.ts
> +  version: '0.7.4-siren.1',
fixes a broken test

2022-10-05 16:02 UTC, Verdagio commented
Note, repositioning nodes on the graph on combo expansion is pushed out to the hard cut tasks https://sirensolutions.atlassian.net/browse/INVE-19841

2022-10-05 16:13 UTC, Verdagio commented on packages/core/src/graph/controller/item.ts
> +      }, 200);
There's some race condition happening here requiring this action to be delayed

https://user-images.githubusercontent.com/15673201/194109893-7b981b0e-0271-4246-9f4d-3a776f2e726a.mov

2022-10-06 13:16 UTC, Verdagio commented on packages/core/src/graph/controller/item.ts
> +      parentBbox.width += 10;
adds buffer to prevent child circles running out of bounds

2022-10-06 13:17 UTC, Verdagio commented
@daniele-pini @TonyN96 this one is ready now

2022-10-07 07:31 UTC, daniele-pini requested changes

2022-10-07 07:31 UTC, daniele-pini commented on packages/core/src/graph/controller/item.ts
> +    }, 0);
You should use this one instead: https://github.com/sirensolutions/G6/blob/2c326f07eb9300c5fd4675c9034270100ccc9cbf/packages/core/src/graph/graph.ts#L1964-L2018

Note how that one also travels up the combo tree hierarchy. And check if that works without the `setTimeout`, too.

2022-10-10 09:09 UTC, Blakko reviewed
Would it be possible to have the child combo to not go outside of the parent?

2022-10-10 10:06 UTC, daniele-pini commented
@Blakko, we're revising the approach - turns out there's actually a bug when _making_ groups, which prevents a correct update. When we fix that, children should placed correctly inside their parents.

2022-10-11 15:15 UTC, Verdagio commented
> Would it be possible to have the child combo to not go outside of the parent?

@Blakko The recording is out of date, this is current behaviour (as per this pr) note looks like master has a bug requiring an additional click away in order for the last action to happen?

https://user-images.githubusercontent.com/15673201/195130663-daf4a6f6-9815-4e28-8637-c9ac516829aa.mov

2022-10-13 13:47 UTC, Blakko commented
> note looks like master has a bug requiring an additional click away in order for the last action to happen?

@Verdagio yes we have a PR in review that will fix that issue

2022-10-14 15:14 UTC, daniele-pini commented
Superseded by #50.

2022-10-14 15:14 UTC, closed without merging