Version 4.8.2
sirensolutions/G6 pull request #56
Opened 2023-01-03 11:49 UTC by niknbr

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] commit message follows commit guidelines

##### Description of change

2023-01-03 11:49 UTC, niknbr commented
Closed for #55

2023-01-03 12:40 UTC, niknbr commented
Two test failures

```
 FAIL  tests/unit/graph/graph-spec.ts
  ● Test suite failed to run

      ● redo stack & undo stack › fill undo stack

        expect(received).toBe(expected) // Object.is equality

        Expected: 1
        Received: 0

          1562 |     let undoStack = stackData.undoStack;
          1563 |     let redoStack = stackData.redoStack;
        > 1564 |     expect(undoStack.length).toBe(1);
               |                              ^
          1565 |     expect(undoStack[0].action).toEqual('render');
          1566 |     expect(undoStack[0].data.after.nodes.length).toEqual(2);
          1567 |     expect(redoStack.length).toBe(0);

      at Object.<anonymous> (tests/unit/graph/graph-spec.ts:1564:30)
```
☝️ Failing upstream. Caused by [this](https://github.com/antvis/G6/pull/4178/commits/69a861736ea35b6586cb5b89d51c85d6713005f6) change

```
     ● states › should change data and swap initial states on updated item if model has it
          expect(received).toEqual(expected) // deep equality
          - Expected  - 4
          + Received  + 1
          - Array [
          -   "appliedOnNodeNew",
          -   "multipleOnNodeNew:valueNew",
          - ]
          + Array []
            1746 |     });
            1747 |
          > 1748 |     expect(graph.findById('node1').getStates()).toEqual(['appliedOnNodeNew', 'multipleOnNodeNew:valueNew']);
                 |                                                 ^
            1749 |   });
            1750 |
            1751 |   it('should change data and apply initial styles on added item if model has it', () => {
      at Object.<anonymous> (tests/unit/graph/graph-spec.ts:1748:49)
```
☝️ Already failing on master. Not related to this PR.

2023-01-03 16:02 UTC, Blakko approved these changes

2023-01-03 16:04 UTC, Blakko requested changes

2023-01-03 16:04 UTC, Blakko commented on packages/pc/src/global.ts
> -  version: '0.7.10-siren.0',
This should be updated

2023-01-03 16:52 UTC, niknbr commented on packages/pc/src/global.ts
> -  version: '0.7.10-siren.0',
missed bump versions. Updated

2023-01-04 09:29 UTC, Blakko approved these changes

2023-01-04 11:26 UTC, merged